#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef VHSTRESSTEMPLLIB_SWIFT_H
#define VHSTRESSTEMPLLIB_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="vhStressTemplLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC16vhStressTemplLib8vhDfsLib")
@interface vhDfsLib : NSObject
/// Contructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Contructor
/// \param me “hspecg@163.com”
///
/// \param chn Number of  leads, it is 12 or 8(I,II,V1-V6)
///
/// \param uVpb voltage sensitivity, in uv/bit
///
- (nonnull instancetype)initWithMe:(NSString * _Nonnull)me chn:(int16_t)chn uVpb:(double)uVpb OBJC_DESIGNATED_INITIALIZER;
/// Creator
/// \param me “hspecg@163.com”
///
/// \param chn Number of  leads, it is 12 gennerally
///
/// \param double Amplitude sensitivity
///
///
/// returns:
///
/// <ul>
///   <li>
///     true or false
///   </li>
/// </ul>
- (BOOL)createWithMe:(NSString * _Nonnull)me chn:(int16_t)chn uVpb:(double)uVpb SWIFT_WARN_UNUSED_RESULT;
/// Double sampling  rate
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     data: a group 12-lead sampling data or 8-lead. the number of data is the number of leads
///   </li>
///   <li>
///     tow groups of data
///   </li>
/// </ul>
///
/// returns:
///
- (NSArray<NSNumber *> * _Nullable)getDataWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC16vhStressTemplLib12vhFiltersLib")
@interface vhFiltersLib : NSObject
/// Contructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Contructor
/// \param me “hspecg@163.com”
///
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12 or 8(I,II,V1-V6)
///
/// \param freqNotch Frequency of Notch, power frequency
///
/// \param uVpb voltage sensitivity, in uv/bit
///
- (nonnull instancetype)initWithMe:(NSString * _Nonnull)me fs:(int16_t)fs chn:(int16_t)chn freqLpass:(int16_t)freqLpass freqNotch:(int16_t)freqNotch smoothStrength:(int16_t)smoothStrength OBJC_DESIGNATED_INITIALIZER;
/// Creator
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12 gennerally
///
/// \param freqFreq Frequency of lpass filter, generally 40-100Hz
///
/// \param freqNotch Frequency of Notch, power frequency, 50/60Hz
///
/// \param smoothStrength 0: not use smooth, 1: weak, 2: strong
///
///
/// returns:
///
/// <ul>
///   <li>
///     true or false
///   </li>
/// </ul>
- (BOOL)createWithMe:(NSString * _Nonnull)me fs:(int16_t)fs chn:(int16_t)chn freqLpass:(int16_t)freqLpass freqNotch:(int16_t)freqNotch smoothStrength:(int16_t)smoothStrength SWIFT_WARN_UNUSED_RESULT;
/// Update parameters of filters
/// \param fs Samplingrate, in Hz
///
/// \param freqLpass Frequency of lpass filter, generally 40-100Hz
///
/// \param freqNotch Frequency of Notch, power frequency, 50/60Hz
///
/// \param smoothStrength 0: not use smooth, 1: weak, 2: strong
///
///
/// returns:
///
/// <ul>
///   <li>
///     true or false
///   </li>
/// </ul>
- (BOOL)updateWithFs:(int16_t)fs freqLpass:(int16_t)freqLpass freqNotch:(int16_t)freqNotch smoothStrength:(int16_t)smoothStrength SWIFT_WARN_UNUSED_RESULT;
/// Switch On./Off Filters
/// \param onOffLpass lpass filter
///
/// \param onOffNotch notch filter
///
/// \param onOffSmooth smooth filter
///
///
/// returns:
///
- (void)switchFiltersOnOffLpass:(BOOL)onOffLpass onOffNotch:(BOOL)onOffNotch onOffSmooth:(BOOL)onOffSmooth;
/// Do Filters
/// \param data a group 12-lead sampling data or 8-lead. the number of data is the number of leads
///
///
/// returns:
///
/// <ul>
///   <li>
///     filtered data
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)filtersWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC16vhStressTemplLib13vhMeanRRmsLib")
@interface vhMeanRRmsLib : NSObject
/// Contructor
/// /// - Parameters:
/// <ul>
///   <li>
///     fs: Sampling rate in Hz
///   </li>
///   <li>
///     chn: Number of  leads, it is 12 or 8(I,II,V1-V6)
///   </li>
///   <li>
///     freqNotch: Frequency of Notch, power frequency
///   </li>
///   <li>
///     uVpb: voltage sensitivity, in uv/bit
///   </li>
/// </ul>
- (nonnull instancetype)initWithFs:(int16_t)fs chn:(int16_t)chn freqNotch:(int16_t)freqNotch uVpb:(double)uVpb OBJC_DESIGNATED_INITIALIZER;
/// Creator
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12 or 8(I,II,V1-V6)
///
/// \param freqNotch Frequency of Notch, power frequency, 50/60Hz
///
/// \param uVpb voltage sensitivity, in uv/bit
///
///
/// returns:
///
- (void)createWithFs:(int16_t)fs chn:(int16_t)chn freqNotch:(int16_t)freqNotch uVpb:(double)uVpb;
/// Get RR interval in ms
/// \param data a group 12-lead sampling data or 8-lead(I,II,V1-V6)
///
///
/// returns:
///
/// <ul>
///   <li>
///     RR interval in ms
///   </li>
/// </ul>
- (int16_t)meanRRmsWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// Get HR interval in bpm
/// \param data a group 12-lead sampling data or 8-lead(I,II,V1-V6)
///
///
/// returns:
///
/// <ul>
///   <li>
///     HR interval in bpm
///   </li>
/// </ul>
- (int16_t)meanHRWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC16vhStressTemplLib16vhStressTemplLib")
@interface vhStressTemplLib : NSObject
/// Creator
/// \param me hspecg@163.com
///
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12
///
/// \param uVpb voltage sensitivity, in uv/bit
///
/// \param mutex_lock use mutex lock?
///
///
/// returns:
///
/// <ul>
///   <li>
///     true:   sucusessfully
///   </li>
///   <li>
///     false: failure
///   </li>
/// </ul>
- (BOOL)createWithMe:(NSString * _Nonnull)me fs:(int16_t)fs chn:(int16_t)chn uVpb:(double)uVpb mutex_lock:(BOOL)mutex_lock SWIFT_WARN_UNUSED_RESULT;
/// Clear buffer
- (void)destroy;
/// <ul>
///   <li>
///     Use templates of Rest ECG to initilaize…
///   </li>
/// </ul>
/// \param templ 12-lead templates from Rest ECG analysis
///
/// \param posQ QRS onset in samples
///
/// \param posJ QRS offset in samples, J point
///
/// \param postJms ? ms after J point
///
///
/// returns:
///
/// <ul>
///   <li>
///     new 12-lead templates, maybe nil or empty;
///   </li>
/// </ul>
- (NSArray<NSArray<NSNumber *> *> * _Nullable)restTemplWithTempl:(NSArray<NSArray<NSNumber *> *> * _Nonnull)templ posQ:(int16_t)posQ posJ:(int16_t)posJ postJms:(int16_t)postJms SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Get posZ(Zero voltage point), posJ, postJms
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     Array including posZ,posJ in samples and postJms in ms, maybe nil or empty
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)getPos SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Match templates for each group sampling data
///   </li>
/// </ul>
/// \param data a group 12-lead sampling data
///
///
/// returns:
///
/// <ul>
///   <li>
///     new templates or nil or empty
///   </li>
/// </ul>
- (NSArray<NSArray<NSNumber *> *> * _Nullable)matchWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Get new 12-lead templates
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     new templates or nil or empty
///   </li>
/// </ul>
- (NSArray<NSArray<NSNumber *> *> * _Nullable)getTempl SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Set new posZ,posJ
///   </li>
/// </ul>
/// \param posZ new point
///
/// \param posJ new point
///
- (void)setPosWithPosZ:(int16_t)posZ posJ:(int16_t)posJ;
/// <ul>
///   <li>
///     Set new postJms
///   </li>
/// </ul>
/// \param postJms new ms after J point
///
- (void)setPostJmsWithPostJms:(int16_t)postJms;
/// <ul>
///   <li>
///     Get slpoe of ST segment
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     slpoe of ST segment of 12-lead templates, in mV/s
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)getSTslope SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Get value of ST segment
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     value of ST segment of 12-lead templates, in uV
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)getSTuv SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Calcualte heart rate when sampling
///     <ul>
///       <li>
///         Parameters:
///         <ul>
///           <li>
///             data1: sampling data of 1st lead in 12-lead
///           </li>
///           <li>
///             data2： sampling data of 2nd lead in 12-lead
///           </li>
///           <li>
///             data3: sampling data of 3rd lead in 12-lead
///           </li>
///         </ul>
///       </li>
///       <li>
///         Returns:
///         <ul>
///           <li>
///             heart rate: find a reasonable heart rate
///           </li>
///           <li>
///             0: heart rate not found
///           </li>
///         </ul>
///       </li>
///     </ul>
///   </li>
/// </ul>
- (int16_t)getMeanHRWithData1:(int16_t)data1 data2:(int16_t)data2 data3:(int16_t)data3 SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Calculate Duke score
///     <ul>
///       <li>
///         Parameters:
///         <ul>
///           <li>
///             stressSeconds: Stress duration with seconds
///           </li>
///           <li>
///             deepestSTwithmV: ST depression with mV
///           </li>
///           <li>
///             anginaPectoris: Angina pectoris with 0:  None, 1: No-limiting, 2: Limiting
///           </li>
///         </ul>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (int16_t)getDukeWithStressSeconds:(int16_t)seconds deepestSTwithmV:(float)mV anginaPectoris:(int16_t)index SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Calculate PWC130/150/170
///     <ul>
///       <li>
///         Parameters:
///         <ul>
///           <li>
///             power: Power value Array in W during Stress stage
///           </li>
///           <li>
///             hr: heart rate Array  in bpm relate to power
///           </li>
///         </ul>
///       </li>
///       <li>
///         Returns:
///         <ul>
///           <li>
///             PWC array with 3 elements, -1 if Invalibale
///           </li>
///         </ul>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (NSArray<NSNumber *> * _Nullable)getPWCWithPower:(NSArray<NSNumber *> * _Nonnull)power andHR:(NSArray<NSNumber *> * _Nonnull)hr SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef VHSTRESSTEMPLLIB_SWIFT_H
#define VHSTRESSTEMPLLIB_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="vhStressTemplLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC16vhStressTemplLib8vhDfsLib")
@interface vhDfsLib : NSObject
/// Contructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Contructor
/// \param me “hspecg@163.com”
///
/// \param chn Number of  leads, it is 12 or 8(I,II,V1-V6)
///
/// \param uVpb voltage sensitivity, in uv/bit
///
- (nonnull instancetype)initWithMe:(NSString * _Nonnull)me chn:(int16_t)chn uVpb:(double)uVpb OBJC_DESIGNATED_INITIALIZER;
/// Creator
/// \param me “hspecg@163.com”
///
/// \param chn Number of  leads, it is 12 gennerally
///
/// \param double Amplitude sensitivity
///
///
/// returns:
///
/// <ul>
///   <li>
///     true or false
///   </li>
/// </ul>
- (BOOL)createWithMe:(NSString * _Nonnull)me chn:(int16_t)chn uVpb:(double)uVpb SWIFT_WARN_UNUSED_RESULT;
/// Double sampling  rate
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     data: a group 12-lead sampling data or 8-lead. the number of data is the number of leads
///   </li>
///   <li>
///     tow groups of data
///   </li>
/// </ul>
///
/// returns:
///
- (NSArray<NSNumber *> * _Nullable)getDataWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC16vhStressTemplLib12vhFiltersLib")
@interface vhFiltersLib : NSObject
/// Contructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Contructor
/// \param me “hspecg@163.com”
///
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12 or 8(I,II,V1-V6)
///
/// \param freqNotch Frequency of Notch, power frequency
///
/// \param uVpb voltage sensitivity, in uv/bit
///
- (nonnull instancetype)initWithMe:(NSString * _Nonnull)me fs:(int16_t)fs chn:(int16_t)chn freqLpass:(int16_t)freqLpass freqNotch:(int16_t)freqNotch smoothStrength:(int16_t)smoothStrength OBJC_DESIGNATED_INITIALIZER;
/// Creator
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12 gennerally
///
/// \param freqFreq Frequency of lpass filter, generally 40-100Hz
///
/// \param freqNotch Frequency of Notch, power frequency, 50/60Hz
///
/// \param smoothStrength 0: not use smooth, 1: weak, 2: strong
///
///
/// returns:
///
/// <ul>
///   <li>
///     true or false
///   </li>
/// </ul>
- (BOOL)createWithMe:(NSString * _Nonnull)me fs:(int16_t)fs chn:(int16_t)chn freqLpass:(int16_t)freqLpass freqNotch:(int16_t)freqNotch smoothStrength:(int16_t)smoothStrength SWIFT_WARN_UNUSED_RESULT;
/// Update parameters of filters
/// \param fs Samplingrate, in Hz
///
/// \param freqLpass Frequency of lpass filter, generally 40-100Hz
///
/// \param freqNotch Frequency of Notch, power frequency, 50/60Hz
///
/// \param smoothStrength 0: not use smooth, 1: weak, 2: strong
///
///
/// returns:
///
/// <ul>
///   <li>
///     true or false
///   </li>
/// </ul>
- (BOOL)updateWithFs:(int16_t)fs freqLpass:(int16_t)freqLpass freqNotch:(int16_t)freqNotch smoothStrength:(int16_t)smoothStrength SWIFT_WARN_UNUSED_RESULT;
/// Switch On./Off Filters
/// \param onOffLpass lpass filter
///
/// \param onOffNotch notch filter
///
/// \param onOffSmooth smooth filter
///
///
/// returns:
///
- (void)switchFiltersOnOffLpass:(BOOL)onOffLpass onOffNotch:(BOOL)onOffNotch onOffSmooth:(BOOL)onOffSmooth;
/// Do Filters
/// \param data a group 12-lead sampling data or 8-lead. the number of data is the number of leads
///
///
/// returns:
///
/// <ul>
///   <li>
///     filtered data
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)filtersWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC16vhStressTemplLib13vhMeanRRmsLib")
@interface vhMeanRRmsLib : NSObject
/// Contructor
/// /// - Parameters:
/// <ul>
///   <li>
///     fs: Sampling rate in Hz
///   </li>
///   <li>
///     chn: Number of  leads, it is 12 or 8(I,II,V1-V6)
///   </li>
///   <li>
///     freqNotch: Frequency of Notch, power frequency
///   </li>
///   <li>
///     uVpb: voltage sensitivity, in uv/bit
///   </li>
/// </ul>
- (nonnull instancetype)initWithFs:(int16_t)fs chn:(int16_t)chn freqNotch:(int16_t)freqNotch uVpb:(double)uVpb OBJC_DESIGNATED_INITIALIZER;
/// Creator
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12 or 8(I,II,V1-V6)
///
/// \param freqNotch Frequency of Notch, power frequency, 50/60Hz
///
/// \param uVpb voltage sensitivity, in uv/bit
///
///
/// returns:
///
- (void)createWithFs:(int16_t)fs chn:(int16_t)chn freqNotch:(int16_t)freqNotch uVpb:(double)uVpb;
/// Get RR interval in ms
/// \param data a group 12-lead sampling data or 8-lead(I,II,V1-V6)
///
///
/// returns:
///
/// <ul>
///   <li>
///     RR interval in ms
///   </li>
/// </ul>
- (int16_t)meanRRmsWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// Get HR interval in bpm
/// \param data a group 12-lead sampling data or 8-lead(I,II,V1-V6)
///
///
/// returns:
///
/// <ul>
///   <li>
///     HR interval in bpm
///   </li>
/// </ul>
- (int16_t)meanHRWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC16vhStressTemplLib16vhStressTemplLib")
@interface vhStressTemplLib : NSObject
/// Creator
/// \param me hspecg@163.com
///
/// \param fs Sampling rate in Hz
///
/// \param chn Number of  leads, it is 12
///
/// \param uVpb voltage sensitivity, in uv/bit
///
/// \param mutex_lock use mutex lock?
///
///
/// returns:
///
/// <ul>
///   <li>
///     true:   sucusessfully
///   </li>
///   <li>
///     false: failure
///   </li>
/// </ul>
- (BOOL)createWithMe:(NSString * _Nonnull)me fs:(int16_t)fs chn:(int16_t)chn uVpb:(double)uVpb mutex_lock:(BOOL)mutex_lock SWIFT_WARN_UNUSED_RESULT;
/// Clear buffer
- (void)destroy;
/// <ul>
///   <li>
///     Use templates of Rest ECG to initilaize…
///   </li>
/// </ul>
/// \param templ 12-lead templates from Rest ECG analysis
///
/// \param posQ QRS onset in samples
///
/// \param posJ QRS offset in samples, J point
///
/// \param postJms ? ms after J point
///
///
/// returns:
///
/// <ul>
///   <li>
///     new 12-lead templates, maybe nil or empty;
///   </li>
/// </ul>
- (NSArray<NSArray<NSNumber *> *> * _Nullable)restTemplWithTempl:(NSArray<NSArray<NSNumber *> *> * _Nonnull)templ posQ:(int16_t)posQ posJ:(int16_t)posJ postJms:(int16_t)postJms SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Get posZ(Zero voltage point), posJ, postJms
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     Array including posZ,posJ in samples and postJms in ms, maybe nil or empty
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)getPos SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Match templates for each group sampling data
///   </li>
/// </ul>
/// \param data a group 12-lead sampling data
///
///
/// returns:
///
/// <ul>
///   <li>
///     new templates or nil or empty
///   </li>
/// </ul>
- (NSArray<NSArray<NSNumber *> *> * _Nullable)matchWithData:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Get new 12-lead templates
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     new templates or nil or empty
///   </li>
/// </ul>
- (NSArray<NSArray<NSNumber *> *> * _Nullable)getTempl SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Set new posZ,posJ
///   </li>
/// </ul>
/// \param posZ new point
///
/// \param posJ new point
///
- (void)setPosWithPosZ:(int16_t)posZ posJ:(int16_t)posJ;
/// <ul>
///   <li>
///     Set new postJms
///   </li>
/// </ul>
/// \param postJms new ms after J point
///
- (void)setPostJmsWithPostJms:(int16_t)postJms;
/// <ul>
///   <li>
///     Get slpoe of ST segment
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     slpoe of ST segment of 12-lead templates, in mV/s
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)getSTslope SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Get value of ST segment
///   </li>
/// </ul>
///
/// returns:
///
/// <ul>
///   <li>
///     value of ST segment of 12-lead templates, in uV
///   </li>
/// </ul>
- (NSArray<NSNumber *> * _Nullable)getSTuv SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Calcualte heart rate when sampling
///     <ul>
///       <li>
///         Parameters:
///         <ul>
///           <li>
///             data1: sampling data of 1st lead in 12-lead
///           </li>
///           <li>
///             data2： sampling data of 2nd lead in 12-lead
///           </li>
///           <li>
///             data3: sampling data of 3rd lead in 12-lead
///           </li>
///         </ul>
///       </li>
///       <li>
///         Returns:
///         <ul>
///           <li>
///             heart rate: find a reasonable heart rate
///           </li>
///           <li>
///             0: heart rate not found
///           </li>
///         </ul>
///       </li>
///     </ul>
///   </li>
/// </ul>
- (int16_t)getMeanHRWithData1:(int16_t)data1 data2:(int16_t)data2 data3:(int16_t)data3 SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Calculate Duke score
///     <ul>
///       <li>
///         Parameters:
///         <ul>
///           <li>
///             stressSeconds: Stress duration with seconds
///           </li>
///           <li>
///             deepestSTwithmV: ST depression with mV
///           </li>
///           <li>
///             anginaPectoris: Angina pectoris with 0:  None, 1: No-limiting, 2: Limiting
///           </li>
///         </ul>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (int16_t)getDukeWithStressSeconds:(int16_t)seconds deepestSTwithmV:(float)mV anginaPectoris:(int16_t)index SWIFT_WARN_UNUSED_RESULT;
/// <ul>
///   <li>
///     Calculate PWC130/150/170
///     <ul>
///       <li>
///         Parameters:
///         <ul>
///           <li>
///             power: Power value Array in W during Stress stage
///           </li>
///           <li>
///             hr: heart rate Array  in bpm relate to power
///           </li>
///         </ul>
///       </li>
///       <li>
///         Returns:
///         <ul>
///           <li>
///             PWC array with 3 elements, -1 if Invalibale
///           </li>
///         </ul>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (NSArray<NSNumber *> * _Nullable)getPWCWithPower:(NSArray<NSNumber *> * _Nonnull)power andHR:(NSArray<NSNumber *> * _Nonnull)hr SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
