#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef VHECGTRENDS_SWIFT_H
#define VHECGTRENDS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="vhECGTrends",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class UIColor;
@class NSCoder;
SWIFT_CLASS("_TtC11vhECGTrends19vhECGBackGroundView")
@interface vhECGBackGroundView : UIView
/// 最小单元间距,default:5
@property (nonatomic) double pixPermm;
/// 10mm line color
@property (nonatomic, strong) UIColor * _Nonnull bg10mmColor;
/// 5mm line color
@property (nonatomic, strong) UIColor * _Nonnull bg5mmColor;
/// 1mm line color
@property (nonatomic, strong) UIColor * _Nonnull bg1mmColor;
/// 10mm line width
@property (nonatomic) CGFloat bg10mmWidth;
/// 5mm line width
@property (nonatomic) CGFloat bg5mmWidth;
/// 1mm line width
@property (nonatomic) CGFloat bg1mmWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic) CGRect frame;
- (void)drawRect:(CGRect)rect;
@end

enum vhEcgPaperSpeedType : NSInteger;
enum vhEcgSensitivityType : NSInteger;
enum vhEcgStandardType : NSInteger;
enum vhEcgLeadDisplayType : NSInteger;
enum vhEcgLeadType : NSInteger;
enum vhEcgLeadModeType : NSInteger;
SWIFT_CLASS("_TtC11vhECGTrends13vhECGDrawView")
@interface vhECGDrawView : UIView
@property (nonatomic) double mmPixel;
@property (nonatomic) enum vhEcgPaperSpeedType paperSpeed;
@property (nonatomic) enum vhEcgSensitivityType sensitivity;
@property (nonatomic) enum vhEcgStandardType standardType;
@property (nonatomic) enum vhEcgLeadDisplayType leadDisplay;
@property (nonatomic) enum vhEcgLeadType longLead;
@property (nonatomic) enum vhEcgLeadModeType leadModeType;
@property (nonatomic) double rate;
@property (nonatomic) BOOL isHavBreath;
@property (nonatomic) double ecgLineWidth;
@property (nonatomic, strong) UIColor * _Nonnull ecgLineColor;
@property (nonatomic, strong) UIColor * _Nonnull ecgLostLineColor;
@property (nonatomic, strong) UIColor * _Nonnull ecgDotColor;
@property (nonatomic, strong) UIColor * _Nonnull ecgStandardColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)resetEcgDrawView;
- (void)updateLeads:(NSArray<NSArray<NSNumber *> *> * _Nonnull)leads :(BOOL)animate;
- (void)updateLeadsStatus:(NSArray<NSNumber *> * _Nonnull)leadsStatus;
- (void)updatePlaybackLeads:(NSArray<NSArray<NSArray<NSNumber *> *> *> * _Nonnull)playbackLeads;
- (void)updateBreaths:(double)breaths :(BOOL)animate;
- (void)updatePlaybackBreaths:(NSArray<NSNumber *> * _Nonnull)breaths;
- (void)drawRect:(CGRect)rect;
@end

@protocol vhECGRealTimeViewDelegate;
@class NSString;
SWIFT_CLASS("_TtC11vhECGTrends17vhECGRealTimeView")
@interface vhECGRealTimeView : UIView
/// 是否为回看记录）,default:false
@property (nonatomic) BOOL isRecordData;
@property (nonatomic, weak) id <vhECGRealTimeViewDelegate> _Nullable delegate;
/// 心电页面背景色,default:white
@property (nonatomic, strong) UIColor * _Nonnull background_color;
/// 心电线颜色（导联正常）,default:darkGray
@property (nonatomic, strong) UIColor * _Nonnull ecg_line_color;
/// 心电线颜色（导联异常丢失）,default:red
@property (nonatomic, strong) UIColor * _Nonnull lost_line_color;
/// 心电头标颜色,default:blue
@property (nonatomic, strong) UIColor * _Nonnull ecg_dot_color;
/// 心电定标颜色,default:darkGray
@property (nonatomic, strong) UIColor * _Nonnull standard_text_color;
/// 心电线宽度,default:1.3
@property (nonatomic) CGFloat ecg_line_width;
/// 心电定标显示方式,default:auto
@property (nonatomic) enum vhEcgStandardType standard_style;
/// 方格大小, default:5.0
@property (nonatomic) double pix_per_mm;
/// 采样率, default:500
@property (nonatomic) double rate;
/// 导联布局, default:6x2
@property (nonatomic) enum vhEcgLeadDisplayType leadDisplay;
/// 纸速, default:25 mm/s
@property (nonatomic) enum vhEcgPaperSpeedType paperSpeed;
/// 电压, default:10 mm/mV
@property (nonatomic) enum vhEcgSensitivityType sensitivity;
/// 导联模式, default:std
@property (nonatomic) enum vhEcgLeadModeType leadModeType;
/// 长导联,default:II
@property (nonatomic) enum vhEcgLeadType longLead;
/// 是否有呼吸线
@property (nonatomic) BOOL isHavBreath;
/// 心电滤波信息
@property (nonatomic, copy) NSString * _Nonnull ecgInfoStr;
@property (nonatomic, strong) UIColor * _Nonnull background_board_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_weak_line_color;
@property (nonatomic) CGFloat background_board_line_width;
@property (nonatomic) CGFloat background_line_width;
@property (nonatomic) CGFloat background_weak_line_width;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) CGRect frame;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@interface vhECGRealTimeView (SWIFT_EXTENSION(vhECGTrends))
- (void)cleanViewCache;
- (void)updateLeads:(NSArray<NSArray<NSNumber *> *> * _Nonnull)values;
- (void)updateBreaths:(double)currentBreaths;
- (void)updateLeadsStatus:(NSArray<NSNumber *> * _Nonnull)values;
- (void)playback_updateLeads:(NSArray<NSArray<NSArray<NSNumber *> *> *> * _Nonnull)values;
- (void)playback_updateBreaths:(NSArray<NSNumber *> * _Nonnull)breaths;
@end

SWIFT_PROTOCOL("_TtP11vhECGTrends25vhECGRealTimeViewDelegate_")
@protocol vhECGRealTimeViewDelegate <NSObject>
@optional
/// 双击心电,刷新view事件
- (void)ecgRefreshLeadHandler;
/// 心电View 长导联变化回调
- (void)ecgLongLeadChangeWithType:(enum vhEcgLeadType)type;
@end

typedef SWIFT_ENUM(NSInteger, vhECGSelectArrowType, open) {
  vhECGSelectArrowTypeLeft = 0,
  vhECGSelectArrowTypeRight = 1,
  vhECGSelectArrowTypeUp = 2,
  vhECGSelectArrowTypeDown = 3,
  vhECGSelectArrowTypeAny = 4,
  vhECGSelectArrowTypeUnknown = 5,
};

@class vhECGSelectInfo;
@class UIPopoverPresentationController;
@class UIFont;
@class NSBundle;
SWIFT_CLASS("_TtC11vhECGTrends27vhECGSelectButtonController")
@interface vhECGSelectButtonController : UITableViewController
@property (nonatomic, copy) void (^ _Nullable selectHandle)(vhECGSelectInfo * _Nullable);
/// 注意，要实现其sourceView 和 sourceRect
@property (nonatomic, strong) UIPopoverPresentationController * _Nullable popOver;
@property (nonatomic, copy) NSArray<vhECGSelectInfo *> * _Nonnull dataSources;
@property (nonatomic, copy) NSString * _Nonnull selectStr;
/// optional
/// view设置的宽高，如果实现此设置，则以此设置宽高为主,高度设置为0时，自动总cell高度
@property (nonatomic) CGSize vSize;
@property (nonatomic) CGFloat itemHight;
- (nonnull instancetype)initWithSourceRect:(CGRect)sourceRect sourceView:(UIView * _Nonnull)sourceView arrowType:(enum vhECGSelectArrowType)arrowType OBJC_DESIGNATED_INITIALIZER;
/// 设置Item字体、字颜色、对齐方式
/// \param font 字体
///
/// \param color 字颜色
///
/// \param alignment 对齐方式
///
/// \param selectBgColor 选中背景颜色
///
- (void)ex_setItemWithFont:(UIFont * _Nonnull)font color:(UIColor * _Nonnull)color alignment:(NSTextAlignment)alignment selectBgColor:(UIColor * _Nonnull)selectBgColor;
- (void)viewWillAppear:(BOOL)animated;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@interface vhECGSelectButtonController (SWIFT_EXTENSION(vhECGTrends))
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

enum vhSelectButtonStyle : NSInteger;
SWIFT_CLASS("_TtC11vhECGTrends21vhECGSelectButtonView")
@interface vhECGSelectButtonView : UIControl
/// 回调，选择后当前的数据
@property (nonatomic, copy) void (^ _Nullable changeHandle)(vhECGSelectInfo * _Nonnull);
/// 默认按钮样式为无边框
@property (nonatomic) enum vhSelectButtonStyle style;
/// 按钮当前展示内容
@property (nonatomic, copy) NSString * _Nonnull currentStr;
/// 按钮当前的标签
@property (nonatomic) NSInteger currentIdx;
/// 按钮标题两边边距，默认无边距
@property (nonatomic) CGFloat space;
@property (nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;
/// 列表属性内容(数据源)
@property (nonatomic, copy) NSArray<vhECGSelectInfo *> * _Nonnull dataSources;
/// listView 高度设置为0时，自动总cell高度
@property (nonatomic) CGSize listViewSize;
/// 构造按钮当前展示内容的字号大小、颜色、对齐方式， 和选择列表的字号大小、颜色、对齐方式、选中颜色
- (nonnull instancetype)initWithEx_titleFont:(UIFont * _Nonnull)ex_titleFont titleColor:(UIColor * _Nonnull)titleColor titleAlignment:(NSTextAlignment)titleAlignment itemFont:(UIFont * _Nonnull)itemFont itemColor:(UIColor * _Nonnull)itemColor itemAlignment:(NSTextAlignment)itemAlignment itemSeleBgColor:(UIColor * _Nonnull)itemSeleBgColor;
/// public list item
- (void)ex_setViewWithTitleFont:(UIFont * _Nonnull)titleFont titleColor:(UIColor * _Nonnull)titleColor titleAlignment:(NSTextAlignment)titleAlignment itemFont:(UIFont * _Nonnull)itemFont itemColor:(UIColor * _Nonnull)itemColor itemAlignment:(NSTextAlignment)itemAlignment itemSeleBgColor:(UIColor * _Nonnull)itemSeleBgColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// 选择框的数据结构
SWIFT_CLASS("_TtC11vhECGTrends15vhECGSelectInfo")
@interface vhECGSelectInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) NSInteger sign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol vhECGTrendsViewDelegate;
SWIFT_CLASS("_TtC11vhECGTrends15vhECGTrendsView")
@interface vhECGTrendsView : UIView
@property (nonatomic) BOOL isRecordData;
@property (nonatomic, weak) id <vhECGTrendsViewDelegate> _Nullable delegate;
@property (nonatomic, strong) UIColor * _Nonnull background_color;
@property (nonatomic, strong) UIColor * _Nonnull ecg_line_color;
@property (nonatomic, strong) UIColor * _Nonnull lost_line_color;
@property (nonatomic, strong) UIColor * _Nonnull ecg_dot_color;
@property (nonatomic, strong) UIColor * _Nonnull standard_text_color;
@property (nonatomic) CGFloat ecg_line_width;
@property (nonatomic) enum vhEcgStandardType standard_style;
@property (nonatomic) double pix_per_mm;
@property (nonatomic) double rate;
@property (nonatomic) enum vhEcgLeadDisplayType leadDisplay;
@property (nonatomic) enum vhEcgPaperSpeedType paperSpeed;
@property (nonatomic) enum vhEcgSensitivityType sensitivity;
@property (nonatomic) enum vhEcgLeadModeType leadModeType;
@property (nonatomic) enum vhEcgLeadType longLead;
@property (nonatomic) BOOL isHavBreath;
@property (nonatomic, copy) NSString * _Nonnull ecgInfoStr;
@property (nonatomic, strong) UIColor * _Nonnull background_board_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_weak_line_color;
@property (nonatomic) CGFloat background_board_line_width;
@property (nonatomic) CGFloat background_line_width;
@property (nonatomic) CGFloat background_weak_line_width;
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@interface vhECGTrendsView (SWIFT_EXTENSION(vhECGTrends)) <vhECGRealTimeViewDelegate>
- (void)ecgRefreshLeadHandler;
- (void)ecgLongLeadChangeWithType:(enum vhEcgLeadType)type;
@end

@interface vhECGTrendsView (SWIFT_EXTENSION(vhECGTrends))
- (void)cleanViewCache;
- (void)updateLeads:(NSArray<NSArray<NSNumber *> *> * _Nonnull)values;
- (void)updateBreaths:(double)currentBreaths;
- (void)updateLeadsStatus:(NSArray<NSNumber *> * _Nonnull)values;
- (void)playback_updateLeads:(NSArray<NSArray<NSArray<NSNumber *> *> *> * _Nonnull)values;
- (void)playback_updateBreaths:(NSArray<NSNumber *> * _Nonnull)breaths;
@end

SWIFT_PROTOCOL("_TtP11vhECGTrends23vhECGTrendsViewDelegate_")
@protocol vhECGTrendsViewDelegate <NSObject>
@optional
/// 心电View 承受最大长度数据数量
- (void)ecgChangeShowMaxCountWithMaxDisplayCount:(NSInteger)maxDisplayCount maxLongCount:(NSInteger)maxLongCount maxBreathCount:(NSInteger)maxBreathCount;
/// 心电View 纸速变化回调
- (void)ecgPaperSpeedChangeWithType:(enum vhEcgPaperSpeedType)type;
/// 心电View 电压变化回调
- (void)ecgSensitivityChangeWithType:(enum vhEcgSensitivityType)type;
/// 心电View 长按可切换导联布局，变化回调
- (void)ecgLeadDisplayChangeWithType:(enum vhEcgLeadDisplayType)type;
/// 双击心电,刷新view事件
- (void)ecgRefreshLeadHandler;
/// 心电View 长导联变化回调
- (void)ecgLongLeadChangeWithType:(enum vhEcgLeadType)type;
/// 心电View 导联模式变化回调
- (void)ecgLeadModeChangeWithType:(enum vhEcgLeadModeType)type;
/// 心电View 记录后退，前进按钮回调
- (void)ecgPre_or_nextHandlerWithIsPre:(BOOL)isPre;
@end

/// 导联布局
typedef SWIFT_ENUM(NSInteger, vhEcgLeadDisplayType, open) {
  vhEcgLeadDisplayTypeLead_3x4 = 0,
  vhEcgLeadDisplayTypeLead_6x2 = 1,
  vhEcgLeadDisplayTypeLead_12x1 = 2,
};

/// 导联模式
typedef SWIFT_ENUM(NSInteger, vhEcgLeadModeType, open) {
  vhEcgLeadModeTypeStd = 0,
  vhEcgLeadModeTypeStd_rb = 1,
  vhEcgLeadModeTypeF = 2,
  vhEcgLeadModeTypeF_rb = 3,
};

/// 导联布局,枚举int为适配OC语言，不可作为数据下标使用
typedef SWIFT_ENUM(NSInteger, vhEcgLeadType, open) {
  vhEcgLeadTypeI = 0,
  vhEcgLeadTypeII = 1,
  vhEcgLeadTypeIII = 2,
  vhEcgLeadTypeAVR = 3,
  vhEcgLeadTypeAVL = 4,
  vhEcgLeadTypeAVF = 5,
  vhEcgLeadTypeV1 = 6,
  vhEcgLeadTypeV2 = 7,
  vhEcgLeadTypeV3 = 8,
  vhEcgLeadTypeV4 = 9,
  vhEcgLeadTypeV5 = 10,
  vhEcgLeadTypeV6 = 11,
  vhEcgLeadTypeV3R = 12,
  vhEcgLeadTypeV4R = 13,
  vhEcgLeadTypeV5R = 14,
  vhEcgLeadTypeV7 = 15,
  vhEcgLeadTypeV8 = 16,
  vhEcgLeadTypeV9 = 17,
  vhEcgLeadTypeAll = 18,
};

/// 走纸速度
typedef SWIFT_ENUM(NSInteger, vhEcgPaperSpeedType, open) {
  vhEcgPaperSpeedTypeHalf = 0,
  vhEcgPaperSpeedTypeNormal = 1,
  vhEcgPaperSpeedTypeDouble = 2,
};

/// 电压 增益
typedef SWIFT_ENUM(NSInteger, vhEcgSensitivityType, open) {
  vhEcgSensitivityTypeHalf = 0,
  vhEcgSensitivityTypeNormal = 1,
  vhEcgSensitivityTypeDouble = 2,
};

/// 心电定标显示方式
typedef SWIFT_ENUM(NSInteger, vhEcgStandardType, open) {
  vhEcgStandardTypeAuto = 0,
  vhEcgStandardTypeShow = 1,
  vhEcgStandardTypeHidden = 2,
};

/// 按钮样式
typedef SWIFT_ENUM(NSInteger, vhSelectButtonStyle, open) {
  vhSelectButtonStyleNormal = 0,
  vhSelectButtonStyleBorder = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef VHECGTRENDS_SWIFT_H
#define VHECGTRENDS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="vhECGTrends",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class UIColor;
@class NSCoder;
SWIFT_CLASS("_TtC11vhECGTrends19vhECGBackGroundView")
@interface vhECGBackGroundView : UIView
/// 最小单元间距,default:5
@property (nonatomic) double pixPermm;
/// 10mm line color
@property (nonatomic, strong) UIColor * _Nonnull bg10mmColor;
/// 5mm line color
@property (nonatomic, strong) UIColor * _Nonnull bg5mmColor;
/// 1mm line color
@property (nonatomic, strong) UIColor * _Nonnull bg1mmColor;
/// 10mm line width
@property (nonatomic) CGFloat bg10mmWidth;
/// 5mm line width
@property (nonatomic) CGFloat bg5mmWidth;
/// 1mm line width
@property (nonatomic) CGFloat bg1mmWidth;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic) CGRect frame;
- (void)drawRect:(CGRect)rect;
@end

enum vhEcgPaperSpeedType : NSInteger;
enum vhEcgSensitivityType : NSInteger;
enum vhEcgStandardType : NSInteger;
enum vhEcgLeadDisplayType : NSInteger;
enum vhEcgLeadType : NSInteger;
enum vhEcgLeadModeType : NSInteger;
SWIFT_CLASS("_TtC11vhECGTrends13vhECGDrawView")
@interface vhECGDrawView : UIView
@property (nonatomic) double mmPixel;
@property (nonatomic) enum vhEcgPaperSpeedType paperSpeed;
@property (nonatomic) enum vhEcgSensitivityType sensitivity;
@property (nonatomic) enum vhEcgStandardType standardType;
@property (nonatomic) enum vhEcgLeadDisplayType leadDisplay;
@property (nonatomic) enum vhEcgLeadType longLead;
@property (nonatomic) enum vhEcgLeadModeType leadModeType;
@property (nonatomic) double rate;
@property (nonatomic) BOOL isHavBreath;
@property (nonatomic) double ecgLineWidth;
@property (nonatomic, strong) UIColor * _Nonnull ecgLineColor;
@property (nonatomic, strong) UIColor * _Nonnull ecgLostLineColor;
@property (nonatomic, strong) UIColor * _Nonnull ecgDotColor;
@property (nonatomic, strong) UIColor * _Nonnull ecgStandardColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)resetEcgDrawView;
- (void)updateLeads:(NSArray<NSArray<NSNumber *> *> * _Nonnull)leads :(BOOL)animate;
- (void)updateLeadsStatus:(NSArray<NSNumber *> * _Nonnull)leadsStatus;
- (void)updatePlaybackLeads:(NSArray<NSArray<NSArray<NSNumber *> *> *> * _Nonnull)playbackLeads;
- (void)updateBreaths:(double)breaths :(BOOL)animate;
- (void)updatePlaybackBreaths:(NSArray<NSNumber *> * _Nonnull)breaths;
- (void)drawRect:(CGRect)rect;
@end

@protocol vhECGRealTimeViewDelegate;
@class NSString;
SWIFT_CLASS("_TtC11vhECGTrends17vhECGRealTimeView")
@interface vhECGRealTimeView : UIView
/// 是否为回看记录）,default:false
@property (nonatomic) BOOL isRecordData;
@property (nonatomic, weak) id <vhECGRealTimeViewDelegate> _Nullable delegate;
/// 心电页面背景色,default:white
@property (nonatomic, strong) UIColor * _Nonnull background_color;
/// 心电线颜色（导联正常）,default:darkGray
@property (nonatomic, strong) UIColor * _Nonnull ecg_line_color;
/// 心电线颜色（导联异常丢失）,default:red
@property (nonatomic, strong) UIColor * _Nonnull lost_line_color;
/// 心电头标颜色,default:blue
@property (nonatomic, strong) UIColor * _Nonnull ecg_dot_color;
/// 心电定标颜色,default:darkGray
@property (nonatomic, strong) UIColor * _Nonnull standard_text_color;
/// 心电线宽度,default:1.3
@property (nonatomic) CGFloat ecg_line_width;
/// 心电定标显示方式,default:auto
@property (nonatomic) enum vhEcgStandardType standard_style;
/// 方格大小, default:5.0
@property (nonatomic) double pix_per_mm;
/// 采样率, default:500
@property (nonatomic) double rate;
/// 导联布局, default:6x2
@property (nonatomic) enum vhEcgLeadDisplayType leadDisplay;
/// 纸速, default:25 mm/s
@property (nonatomic) enum vhEcgPaperSpeedType paperSpeed;
/// 电压, default:10 mm/mV
@property (nonatomic) enum vhEcgSensitivityType sensitivity;
/// 导联模式, default:std
@property (nonatomic) enum vhEcgLeadModeType leadModeType;
/// 长导联,default:II
@property (nonatomic) enum vhEcgLeadType longLead;
/// 是否有呼吸线
@property (nonatomic) BOOL isHavBreath;
/// 心电滤波信息
@property (nonatomic, copy) NSString * _Nonnull ecgInfoStr;
@property (nonatomic, strong) UIColor * _Nonnull background_board_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_weak_line_color;
@property (nonatomic) CGFloat background_board_line_width;
@property (nonatomic) CGFloat background_line_width;
@property (nonatomic) CGFloat background_weak_line_width;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) CGRect frame;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@interface vhECGRealTimeView (SWIFT_EXTENSION(vhECGTrends))
- (void)cleanViewCache;
- (void)updateLeads:(NSArray<NSArray<NSNumber *> *> * _Nonnull)values;
- (void)updateBreaths:(double)currentBreaths;
- (void)updateLeadsStatus:(NSArray<NSNumber *> * _Nonnull)values;
- (void)playback_updateLeads:(NSArray<NSArray<NSArray<NSNumber *> *> *> * _Nonnull)values;
- (void)playback_updateBreaths:(NSArray<NSNumber *> * _Nonnull)breaths;
@end

SWIFT_PROTOCOL("_TtP11vhECGTrends25vhECGRealTimeViewDelegate_")
@protocol vhECGRealTimeViewDelegate <NSObject>
@optional
/// 双击心电,刷新view事件
- (void)ecgRefreshLeadHandler;
/// 心电View 长导联变化回调
- (void)ecgLongLeadChangeWithType:(enum vhEcgLeadType)type;
@end

typedef SWIFT_ENUM(NSInteger, vhECGSelectArrowType, open) {
  vhECGSelectArrowTypeLeft = 0,
  vhECGSelectArrowTypeRight = 1,
  vhECGSelectArrowTypeUp = 2,
  vhECGSelectArrowTypeDown = 3,
  vhECGSelectArrowTypeAny = 4,
  vhECGSelectArrowTypeUnknown = 5,
};

@class vhECGSelectInfo;
@class UIPopoverPresentationController;
@class UIFont;
@class NSBundle;
SWIFT_CLASS("_TtC11vhECGTrends27vhECGSelectButtonController")
@interface vhECGSelectButtonController : UITableViewController
@property (nonatomic, copy) void (^ _Nullable selectHandle)(vhECGSelectInfo * _Nullable);
/// 注意，要实现其sourceView 和 sourceRect
@property (nonatomic, strong) UIPopoverPresentationController * _Nullable popOver;
@property (nonatomic, copy) NSArray<vhECGSelectInfo *> * _Nonnull dataSources;
@property (nonatomic, copy) NSString * _Nonnull selectStr;
/// optional
/// view设置的宽高，如果实现此设置，则以此设置宽高为主,高度设置为0时，自动总cell高度
@property (nonatomic) CGSize vSize;
@property (nonatomic) CGFloat itemHight;
- (nonnull instancetype)initWithSourceRect:(CGRect)sourceRect sourceView:(UIView * _Nonnull)sourceView arrowType:(enum vhECGSelectArrowType)arrowType OBJC_DESIGNATED_INITIALIZER;
/// 设置Item字体、字颜色、对齐方式
/// \param font 字体
///
/// \param color 字颜色
///
/// \param alignment 对齐方式
///
/// \param selectBgColor 选中背景颜色
///
- (void)ex_setItemWithFont:(UIFont * _Nonnull)font color:(UIColor * _Nonnull)color alignment:(NSTextAlignment)alignment selectBgColor:(UIColor * _Nonnull)selectBgColor;
- (void)viewWillAppear:(BOOL)animated;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@interface vhECGSelectButtonController (SWIFT_EXTENSION(vhECGTrends))
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

enum vhSelectButtonStyle : NSInteger;
SWIFT_CLASS("_TtC11vhECGTrends21vhECGSelectButtonView")
@interface vhECGSelectButtonView : UIControl
/// 回调，选择后当前的数据
@property (nonatomic, copy) void (^ _Nullable changeHandle)(vhECGSelectInfo * _Nonnull);
/// 默认按钮样式为无边框
@property (nonatomic) enum vhSelectButtonStyle style;
/// 按钮当前展示内容
@property (nonatomic, copy) NSString * _Nonnull currentStr;
/// 按钮当前的标签
@property (nonatomic) NSInteger currentIdx;
/// 按钮标题两边边距，默认无边距
@property (nonatomic) CGFloat space;
@property (nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;
/// 列表属性内容(数据源)
@property (nonatomic, copy) NSArray<vhECGSelectInfo *> * _Nonnull dataSources;
/// listView 高度设置为0时，自动总cell高度
@property (nonatomic) CGSize listViewSize;
/// 构造按钮当前展示内容的字号大小、颜色、对齐方式， 和选择列表的字号大小、颜色、对齐方式、选中颜色
- (nonnull instancetype)initWithEx_titleFont:(UIFont * _Nonnull)ex_titleFont titleColor:(UIColor * _Nonnull)titleColor titleAlignment:(NSTextAlignment)titleAlignment itemFont:(UIFont * _Nonnull)itemFont itemColor:(UIColor * _Nonnull)itemColor itemAlignment:(NSTextAlignment)itemAlignment itemSeleBgColor:(UIColor * _Nonnull)itemSeleBgColor;
/// public list item
- (void)ex_setViewWithTitleFont:(UIFont * _Nonnull)titleFont titleColor:(UIColor * _Nonnull)titleColor titleAlignment:(NSTextAlignment)titleAlignment itemFont:(UIFont * _Nonnull)itemFont itemColor:(UIColor * _Nonnull)itemColor itemAlignment:(NSTextAlignment)itemAlignment itemSeleBgColor:(UIColor * _Nonnull)itemSeleBgColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// 选择框的数据结构
SWIFT_CLASS("_TtC11vhECGTrends15vhECGSelectInfo")
@interface vhECGSelectInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) NSInteger sign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol vhECGTrendsViewDelegate;
SWIFT_CLASS("_TtC11vhECGTrends15vhECGTrendsView")
@interface vhECGTrendsView : UIView
@property (nonatomic) BOOL isRecordData;
@property (nonatomic, weak) id <vhECGTrendsViewDelegate> _Nullable delegate;
@property (nonatomic, strong) UIColor * _Nonnull background_color;
@property (nonatomic, strong) UIColor * _Nonnull ecg_line_color;
@property (nonatomic, strong) UIColor * _Nonnull lost_line_color;
@property (nonatomic, strong) UIColor * _Nonnull ecg_dot_color;
@property (nonatomic, strong) UIColor * _Nonnull standard_text_color;
@property (nonatomic) CGFloat ecg_line_width;
@property (nonatomic) enum vhEcgStandardType standard_style;
@property (nonatomic) double pix_per_mm;
@property (nonatomic) double rate;
@property (nonatomic) enum vhEcgLeadDisplayType leadDisplay;
@property (nonatomic) enum vhEcgPaperSpeedType paperSpeed;
@property (nonatomic) enum vhEcgSensitivityType sensitivity;
@property (nonatomic) enum vhEcgLeadModeType leadModeType;
@property (nonatomic) enum vhEcgLeadType longLead;
@property (nonatomic) BOOL isHavBreath;
@property (nonatomic, copy) NSString * _Nonnull ecgInfoStr;
@property (nonatomic, strong) UIColor * _Nonnull background_board_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_line_color;
@property (nonatomic, strong) UIColor * _Nonnull background_weak_line_color;
@property (nonatomic) CGFloat background_board_line_width;
@property (nonatomic) CGFloat background_line_width;
@property (nonatomic) CGFloat background_weak_line_width;
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@interface vhECGTrendsView (SWIFT_EXTENSION(vhECGTrends)) <vhECGRealTimeViewDelegate>
- (void)ecgRefreshLeadHandler;
- (void)ecgLongLeadChangeWithType:(enum vhEcgLeadType)type;
@end

@interface vhECGTrendsView (SWIFT_EXTENSION(vhECGTrends))
- (void)cleanViewCache;
- (void)updateLeads:(NSArray<NSArray<NSNumber *> *> * _Nonnull)values;
- (void)updateBreaths:(double)currentBreaths;
- (void)updateLeadsStatus:(NSArray<NSNumber *> * _Nonnull)values;
- (void)playback_updateLeads:(NSArray<NSArray<NSArray<NSNumber *> *> *> * _Nonnull)values;
- (void)playback_updateBreaths:(NSArray<NSNumber *> * _Nonnull)breaths;
@end

SWIFT_PROTOCOL("_TtP11vhECGTrends23vhECGTrendsViewDelegate_")
@protocol vhECGTrendsViewDelegate <NSObject>
@optional
/// 心电View 承受最大长度数据数量
- (void)ecgChangeShowMaxCountWithMaxDisplayCount:(NSInteger)maxDisplayCount maxLongCount:(NSInteger)maxLongCount maxBreathCount:(NSInteger)maxBreathCount;
/// 心电View 纸速变化回调
- (void)ecgPaperSpeedChangeWithType:(enum vhEcgPaperSpeedType)type;
/// 心电View 电压变化回调
- (void)ecgSensitivityChangeWithType:(enum vhEcgSensitivityType)type;
/// 心电View 长按可切换导联布局，变化回调
- (void)ecgLeadDisplayChangeWithType:(enum vhEcgLeadDisplayType)type;
/// 双击心电,刷新view事件
- (void)ecgRefreshLeadHandler;
/// 心电View 长导联变化回调
- (void)ecgLongLeadChangeWithType:(enum vhEcgLeadType)type;
/// 心电View 导联模式变化回调
- (void)ecgLeadModeChangeWithType:(enum vhEcgLeadModeType)type;
/// 心电View 记录后退，前进按钮回调
- (void)ecgPre_or_nextHandlerWithIsPre:(BOOL)isPre;
@end

/// 导联布局
typedef SWIFT_ENUM(NSInteger, vhEcgLeadDisplayType, open) {
  vhEcgLeadDisplayTypeLead_3x4 = 0,
  vhEcgLeadDisplayTypeLead_6x2 = 1,
  vhEcgLeadDisplayTypeLead_12x1 = 2,
};

/// 导联模式
typedef SWIFT_ENUM(NSInteger, vhEcgLeadModeType, open) {
  vhEcgLeadModeTypeStd = 0,
  vhEcgLeadModeTypeStd_rb = 1,
  vhEcgLeadModeTypeF = 2,
  vhEcgLeadModeTypeF_rb = 3,
};

/// 导联布局,枚举int为适配OC语言，不可作为数据下标使用
typedef SWIFT_ENUM(NSInteger, vhEcgLeadType, open) {
  vhEcgLeadTypeI = 0,
  vhEcgLeadTypeII = 1,
  vhEcgLeadTypeIII = 2,
  vhEcgLeadTypeAVR = 3,
  vhEcgLeadTypeAVL = 4,
  vhEcgLeadTypeAVF = 5,
  vhEcgLeadTypeV1 = 6,
  vhEcgLeadTypeV2 = 7,
  vhEcgLeadTypeV3 = 8,
  vhEcgLeadTypeV4 = 9,
  vhEcgLeadTypeV5 = 10,
  vhEcgLeadTypeV6 = 11,
  vhEcgLeadTypeV3R = 12,
  vhEcgLeadTypeV4R = 13,
  vhEcgLeadTypeV5R = 14,
  vhEcgLeadTypeV7 = 15,
  vhEcgLeadTypeV8 = 16,
  vhEcgLeadTypeV9 = 17,
  vhEcgLeadTypeAll = 18,
};

/// 走纸速度
typedef SWIFT_ENUM(NSInteger, vhEcgPaperSpeedType, open) {
  vhEcgPaperSpeedTypeHalf = 0,
  vhEcgPaperSpeedTypeNormal = 1,
  vhEcgPaperSpeedTypeDouble = 2,
};

/// 电压 增益
typedef SWIFT_ENUM(NSInteger, vhEcgSensitivityType, open) {
  vhEcgSensitivityTypeHalf = 0,
  vhEcgSensitivityTypeNormal = 1,
  vhEcgSensitivityTypeDouble = 2,
};

/// 心电定标显示方式
typedef SWIFT_ENUM(NSInteger, vhEcgStandardType, open) {
  vhEcgStandardTypeAuto = 0,
  vhEcgStandardTypeShow = 1,
  vhEcgStandardTypeHidden = 2,
};

/// 按钮样式
typedef SWIFT_ENUM(NSInteger, vhSelectButtonStyle, open) {
  vhSelectButtonStyleNormal = 0,
  vhSelectButtonStyleBorder = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
